#####################################################################
# Spin Figma Tools Dataset Configuration
#####################################################################
# This configuration demonstrates using Figma MCP tools via Spin
# for generating synthetic design assistant training data.
#
# Prerequisites:
#   1. Start the Spin service:
#      cd tools-sdk
#      spin build && spin up
#
#   2. Import tools from Figma MCP server:
#      deepfabric import-tools --transport stdio \
#        --command "npx -y figma-developer-mcp --stdio" \
#        --env "FIGMA_API_KEY=your-key" \
#        --spin http://localhost:3000
#
#   3. Load mock data for realistic responses:
#      cd tools-sdk/examples
#      ./load-figma-mock-data.sh
#
#   4. Run deepfabric:
#      deepfabric start examples/spin-figma.yaml
#####################################################################

# Topic generation - creates a tree of Figma design-related topics
topics:
  prompt: "Design tasks for a Figma design assistant that helps developers understand and implement UI designs"
  mode: graph
  system_prompt: ""
  depth: 5
  degree: 5
  save_as: "figma-topics.jsonl"

  llm:
    provider: "gemini"
    model: "gemini-2.5-flash-lite"
    temperature: 0.8

# Data generation with Figma tool execution
generation:
  system_prompt: |
    You are a Figma design assistant helping developers understand and implement UI designs.
    You have access to tools that can fetch Figma file data and download images.

    When helping with design tasks:
    1. Use get_figma_data to retrieve layout, styling, and component information
    2. Use download_figma_images when the user needs to export icons or images
    3. Provide detailed implementation guidance based on the design data
    4. Explain spacing, colors, typography, and component structure clearly

  conversation:
    type: chain_of_thought
    reasoning_style: agent
    agent_mode: single_turn

  tools:
    # Spin service endpoint for mock tool execution
    spin_endpoint: "http://localhost:3000"
    tool_execute_path: "/mock/execute"

    # Available Figma tools (loaded via import-tools command)
    available:
      - get_figma_data
      - download_figma_images

    max_per_query: 3
    strict: false

    # ReAct loop configuration
    max_agent_steps: 5

  max_retries: 3

  llm:
    provider: "gemini"
    model: "gemini-2.5-flash-lite"
    temperature: 0.4

# Output configuration
output:
  system_prompt: |
    You are a Figma design assistant that helps developers understand and implement UI designs.
    You have access to the following tools:

    - get_figma_data: Fetch comprehensive Figma file data including layout, content, visuals, and component information
    - download_figma_images: Download SVG and PNG images from Figma designs

    When given a task:
    1. Use the appropriate Figma tools to retrieve design information
    2. Analyze the design structure, spacing, colors, and typography
    3. Provide clear implementation guidance for developers
    4. Export images when needed for implementation

  include_system_message: false
  num_samples: 300
  batch_size: 4
  save_as: "figma-dataset.jsonl"
